name: quisp main
on: [push, pull_request]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sfc-aqua/quisp-ci:latest
      credentials:
        username: quisp-bot
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/quisp/quisp
      - name: Check out repository
        uses: actions/checkout@v3
      - name: make eigen
        run: make eigen
      - name: generate makefile
        run: make makefile-lib
      - name: generate message headers
        run: make msgheaders
      - name: make googletest
        run: make googletest
      - name: unit tests and generate coverage report
        run: |
          opp_makemake -f --deep -O out -i ./makefrag -M release --make-so
          make lcov.info
          lcov -r lcov.info 'googletest/*' -o lcov_filtered.info
        working-directory: quisp
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./quisp/lcov_filtered.info
  e2e-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sfc-aqua/quisp-ci:latest
      credentials:
        username: quisp-bot
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/quisp/quisp
      - name: Check out repository
        uses: actions/checkout@v3
      - name: make eigen
        run: make eigen
      - name: generate makefile
        run: make makefile-lib
      - name: generate message headers
        run: make msgheaders
      - name: Run Simulations
        run: /bin/bash test.sh
        working-directory: test
      - name: Check Simulation Results
        run: python -m unittest discover
        working-directory: test

  clang-tidy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sfc-aqua/quisp-ci:latest
      credentials:
        username: quisp-bot
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/quisp/quisp
      - name: Check out repository
        uses: actions/checkout@v3
      - name: make eigen
        run: make eigen
      - name: generate makefile
        run: make makefile-lib
      - name: generate message headers
        run: make msgheaders
      - name: make googletest
        run: make googletest
      - name: clang-tidy
        run: make tidy
  clang-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sfc-aqua/quisp-ci:latest
      credentials:
        username: quisp-bot
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/quisp/quisp
      - name: Check out repository
        uses: actions/checkout@v3
      - name: generate makefile
        run: make makefile-lib
      - name: generate message headers
        run: make msgheaders
      - name: clang-format
        run: make format-ci
